### ISSUE TITLE
provide a way to install the MMT jedit plugin from the big mmt.jar

### ISSUE THREAD

**Issue by tkw1536** [KWARC/MMT#108]
This would make it extremly simple for users to install the jedit plugin. In particular they wouldn't have to ```svn co``` or ```git clone``` the entire repository and we can just give them one jar to download. Additionally users with a running localmh installation could just install the plugin because we automatically download that jar only. 

/cc @florian-rabe @cmaeder

**Comment by cmaeder** [comment]
I had this once already working (https://github.com/KWARC/MMT/commit/c0a63e92f70cc389c39b373fbb26d56eac21a959), but @florian-rabe wanted to use the jars under deploy. https://github.com/KWARC/MMT/blob/master/src/jEdit-mmt/src/resources/mmtplugin.props was adjusted in the above commit.

Furthermore, the current fat mmt.jar, does not contain the jedit stuff. (Building the old fat MMTPlugin.jar was removed from build.sbt)

**Comment by cmaeder** [comment]
Both fat jars also contained different classes for `main` (`info.kwarc.mmt.jeditsetup.Setup` for `MMTPlugin.jar`)

**Comment by florian-rabe** [comment]
I'm fine with having a fat jar - it's a good way to show off how easy MMT is to install.

I only objected to the fat jar all the time because it slowed the testing cycle.
We should have a separate build target for building the fat jar.

Note that the fat jar (as well as the mmt-api.jar) contains multiple main methods. These can be run very easily via "java CLASS.NAME ARGS".

Tom Wiesing wrote on 31.01.2016 14:15 +0100

**Comment by cmaeder** [comment]
In https://github.com/KWARC/MMT/commit/1a9650db9af9f660a2ede2b4dd26dad180321c55 I've added jedit to mmt.jar. However, different setup routines and mmtplugin.props must still be supplied for the fat jar (and don't blame me if both variants diverge or behave differently).

**Comment by florian-rabe** [comment]
That's true unfortunately.

The jedit setup would have to be aware of whether it's run from the fat jar or the single jars.

In the former case, it must
- copy only the fat jar (as opposed all the other jars)
- remove the line listing the dependent jars from the .props file.

cmaeder wrote on 02.02.2016 16:05 +0100

**Comment by cmaeder** [comment]
The file `mmtplugin.props` is part of the resources which is difficult to be different in the slim and the fat jar. Any idea?

**Comment by cmaeder** [comment]
Currently, I see `#plugin.info.kwarc.mmt.jedit.MMTPlugin.jars=...` in `mmtplugin.props`. This would be OK for the fat jar. (Maybe it is a left-over of my earlier change towards a fat jar.) It seems to work for the current jar, too.

**Comment by cmaeder** [comment]
I've also made a second setup script called `setupFat.sh` that installs the fat jar. However, for the other files being copied still the repository needs to be checked out.

Could someone check if jedit works in the same with the fat jar installed? (I somehow do not get rid of my loaded file set.mmt with 200 errors)

**Comment by cmaeder** [comment]
`mmt` has now `:setup` an `:setupjedit` options. However, the files under `deploy/jedit-plugin` should become java resources that are stored within the .jar files.

**Comment by florian-rabe** [comment]
Yes.

I suppose we have to move the folder deploy/jedit-plugin to src/jedit-mmt/resources (or something similar).

Could you do that?

cmaeder wrote on 09.02.2016 16:15 +0100

**Comment by cmaeder** [comment]
`mmt :setup` writes the file  `deploy/main/mmtrc` that is used by a separate call to `mmt :jeditsetup` for the "property for content folder". However, `mmt.jar :jeditsetup` does not pick the file `deploy/main/mmtrc` as it expects configurations only in the folder it resides in.

On the other hand `mmt.jar :setup` correctly sets the "property for content folder", because it internally calls `jeditsetup` with the internally added configuration (for `oaf`).

Maybe the file `deploy/main/mmtrc` should not be written out at all.

**Comment by cmaeder** [comment]
@florian-rabe apart from the sort of "secret" configuration file `deploy/main/mmtrc` this issue is resolved.
