### ISSUE TITLE
all.tex and all.<lang>.tex dependencies

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#149]
```all.<lang>.tex``` should have a build dependency on ```<repos>/lib/pre.<lang>.tex``` or ```<group>/meta-inf/lib/pre.<lang>.tex``` (the same for ```post.tex```; no <lang> here) and file dependencies on ```localpaths.tex``` and ```preamble.tex```. and a directory dependency on all ```*.<lang>.tex```. 
<lang> can be empty for the module signatures in SMGloM and the regular modules in the rest.

**Comment by cmaeder** [comment]
comparing new content with old content of `all.` files (see #125) will detect changes in `pre.` or `post.` files! 

A problem remaining is that `buildDir` is not even called if the corresponding directory has not changed. This could be fixed by calling `buildDir` always and leave the whole up-to-date check (for directories only) to `buildDir`. I did not do this because Indexer and Exporter overwrite `buildDir` and would always produce new output if I do not adjust them.

**Comment by cmaeder** [comment]
Considering (possibly changed) pre. and post. files is a problem for the `latexml` and `pdflatex` target!

**Comment by cmaeder** [comment]
see #165 instead
