### ISSUE TITLE
Fix errorLevel for BuildQueue dependencies

### ISSUE THREAD

**Issue by m-iancu** [KWARC/MMT#150]

**Comment by cmaeder** [comment]
The build queue process inserts an update-task before the same forced task is being inserted.

**Comment by cmaeder** [comment]
When checking for already queued dependencies the priorities/update policies of the associated queue tasks should be taken into account.

**Comment by cmaeder** [comment]
In `smglom/numberfields` the file `arithmetics.omdoc` was never handled, because it was added with high priority as dependency of `absolutevalue.de.omdoc` (after `arithmetics.omdoc` was added explicitely).

Adding something with high priority removes another identical entry (in our case the user supplied `arithmetics.omdoc`). Dependencies are only checked for being up-to-date.

The fix in the build queue now takes the maximal force (that is actually the minimal value) of both task for the task that is kept in the queue.

The option `--force` processes now 129 files. Without the fix only below one hundred files were processed unless also dependencies have been forced which is possible with the new option `--forceDeps`.
