### ISSUE TITLE
MMT should generate all.tex

### ISSUE THREAD

**Issue by tkw1536** [KWARC/MMT#59]
The code was removed from lmh when generation fo content was switched to MMT, hence MMT should handle this generation as well. 

The last working version of the code is at: 
https://github.com/KWARC/localmh/blob/77b9dbe7868c52c8d21dd85a20843826040c80d2/lmh/lib/modules/generators/alltex.py

all.tex generation is special because one file has to be generated PER FOLDER / PER LANGUAGE. If you need to know about how exactly it works, let me know. 

/cc KWARC/localmh#245

**Comment by cmaeder** [comment]
`rbuild alltex <dirnames>` will now create `all.tex` and `all.lang.tex` files if corresponding `[.lang].tex` files exist. 

However, currently, the (language dependent) preamble- and postamble files are not copied to these `all[.lang].tex` files (yet) in order to allow the current pdflatex call to also process these  `all.`-files.

To specifically build `pdf` only for `all.` files a new target `allpdf` has been added. A possible rbuild call is `mmt.jar rbuild alltex_allpdf source`. (The other target `pdflatex` does not process `all.` files.)

In the future, .tex files will be inspected (see #62) for preamble and postamble files, so that adding them back to  `all.` files will not harm.
