### ISSUE TITLE
investigate mmt hanging

### ISSUE THREAD

**Issue by cmaeder** [KWARC/MMT#68]
see #67 and also `nohup nice mmt.jar rbuild --force pdflatex */*/source >& log &` in Mathhub finished processing all files, but mmt did not terminate.

Maybe also xelatex spawns processes that the jvm waits for but looses track off (although these processes finish normally).

**Comment by cmaeder** [comment]
@dginev @florian-rabe http://docs.oracle.com/javase/7/docs/api/java/lang/Process.html mentions
"The methods that create processes may not work well for special processes on certain native platforms, such as native windowing processes, daemon processes, Win16/DOS processes on Microsoft Windows, or shell scripts."

**Comment by dginev** [comment]
Gotta love Java.

It is usually better to use a scripting language as the "glue" that binds all components together, rather than force Java into acting like a shell script.

You can have a bash/perl/python/ruby/php script that manages all components, and make MMT oblivious to the peculiarities of LaTeXML.

**Comment by cmaeder** [comment]
I have not observed this for a while. I suspect the hanging was due to (error) output produced by the latexml server that was not properly handled. This output is now always sent to the console (via "BasicIO.standard(false).daemonized" in class LaTeXML).
 
Therefore `LaTeXML server listening on ...` is shown, whenever `latexmls` starts.
