### ISSUE TITLE
rbuild omdoc --pipe-worker-output should pipe the whole log file

### ISSUE THREAD

**Issue by kohlhase** [KWARC/MMT#78]
It seems to me that only the errors are piped. I would like to have the full log file (including all the files read, ... ) piped into the output

**Comment by cmaeder** [comment]
For `mmt rbuild latexml` or `lmh omdoc` with `--pipe-worker-output` only the output of `latexml` was/is shown. The actual `log` is written to the `.ltxlog` file. 

In my last commit `--pipe-worker-output` will write the log to the console rather than to the `.ltxlog` file.
I've no choice to write both (console and `.ltxlog`) since latexml does not seem to support this.

**Comment by cmaeder** [comment]
I just noticed that without .ltxlog file MMT can parse no errors.

**Comment by kohlhase** [comment]
> I just noticed that without .ltxlog file MMT can parse no errors.

I am not sure that this is a problem. I use ```--pipe-worker-output``` in "local  mode", when I am working on the working copy file per file, then I do not need the error parsing. 
But I will make an issue for latexml asking for having both.

**Comment by cmaeder** [comment]
Unfortunately rerunning the same command without modifier will do nothing since the `.err` file will be update-to-date. I now also insert an error so that at least `--onError` (and `--depsFirst`) will rerun the file (but `--force` is definitely simpler to use). 

Regarding `--depsFirst`: dependent files even in other archives will be processed/checked first
(Since a963ae6558d5b607aa0ee99da106c9c7e990addf also dependent .sms files will created/updated prior to producing omdoc or pdf)

**Comment by cmaeder** [comment]
I now collect all output first and finally print out the log file content and console output (in this order) in one go (until https://github.com/brucemiller/LaTeXML/issues/672 is resolved)
